# Generated by Django 2.0 on 2019-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0003_auto_20191114_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianpu',
            name='DianPuMing',
            field=models.CharField(default='', max_length=200, verbose_name='店铺名'),
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='JianJie',
            field=models.CharField(default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='ShiFuTongGuo',
            field=models.CharField(default='', max_length=200, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='YongYouZhe',
            field=models.CharField(default='', max_length=200, verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='ZhaoPai',
            field=models.CharField(default='', max_length=200, verbose_name='招牌'),
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='ZhuangTai',
            field=models.CharField(default='', max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='lunbotu',
            name='LianJie',
            field=models.CharField(default='', max_length=200, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='lunbotu',
            name='TuPian',
            field=models.CharField(default='', max_length=200, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='JiGuan',
            field=models.CharField(default='', max_length=200, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='MiMa',
            field=models.CharField(default='', max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='MinZu',
            field=models.CharField(default='', max_length=200, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='NianLing',
            field=models.CharField(default='', max_length=200, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='TouXiang',
            field=models.CharField(default='', max_length=200, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='XingBie',
            field=models.CharField(default='', max_length=200, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='XingMing',
            field=models.CharField(default='', max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='ZhangHao',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='账号'),
        ),
    ]
