# Generated by Django 2.0 on 2019-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0004_auto_20191114_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianpu',
            name='ShiFuTongGuo',
            field=models.CharField(default='否', max_length=200, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='ZhuangTai',
            field=models.CharField(default='待审核', max_length=200, verbose_name='状态'),
        ),
    ]
