# Generated by Django 2.0 on 2019-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0006_auto_20191114_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunbotu',
            name='JianJie',
            field=models.CharField(default='', max_length=200, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='lunbotu',
            name='LianJie',
            field=models.CharField(default='', max_length=200, verbose_name='简介'),
        ),
    ]
