# Generated by Django 2.0 on 2019-11-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0009_shangpin_suoshushangdian'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeHu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZhangHao', models.CharField(default='', max_length=200, verbose_name='账号')),
                ('MiMa', models.CharField(default='', max_length=200, verbose_name='密码')),
                ('YongHuMing', models.CharField(default='', max_length=200, verbose_name='用户名')),
                ('XingBie', models.CharField(default='', max_length=200, verbose_name='性别')),
                ('NianLing', models.CharField(default='', max_length=200, verbose_name='年龄')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '客户列表',
            },
        ),
    ]
