# Generated by Django 2.0 on 2019-12-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0011_dianpu_leixing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GouWuChe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShangPin', models.CharField(default='', max_length=200, verbose_name='商品')),
                ('GouMaiRen', models.CharField(default='', max_length=200, verbose_name='购买人')),
                ('ShuLiang', models.CharField(default='', max_length=200, verbose_name='数量')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '购物车列表',
            },
        ),
    ]
