# Generated by Django 2.0 on 2019-12-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0012_gouwuche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gouwuche',
            name='ShangPin',
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='GouMaiShuLiang',
            field=models.CharField(default='', max_length=200, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='JiaGe',
            field=models.CharField(default='', max_length=200, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='JianJie',
            field=models.CharField(default='', max_length=200, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='LeiXing',
            field=models.CharField(default='', max_length=200, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='ShangPinMing',
            field=models.CharField(default='', max_length=200, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='SuoShuShangDian',
            field=models.CharField(default='', max_length=200, verbose_name='所属商店'),
        ),
        migrations.AddField(
            model_name='gouwuche',
            name='TuPian',
            field=models.CharField(default='', max_length=200, verbose_name='图片'),
        ),
    ]
