# Generated by Django 2.0 on 2019-12-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0013_auto_20191203_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShouHuoDiZhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sheng', models.CharField(default='', max_length=200, verbose_name='省')),
                ('Shi', models.CharField(default='', max_length=200, verbose_name='市')),
                ('Qu', models.CharField(default='', max_length=200, verbose_name='区')),
                ('JieDao', models.CharField(default='', max_length=200, verbose_name='街道')),
                ('DianHua', models.CharField(default='', max_length=200, verbose_name='电话')),
                ('XingMing', models.CharField(default='', max_length=200, verbose_name='姓名')),
                ('YouBian', models.CharField(default='', max_length=200, verbose_name='邮编')),
                ('SuoShuYongHu', models.CharField(default='', max_length=200, verbose_name='所属用户')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '收货地址列表',
            },
        ),
    ]
