# Generated by Django 2.0 on 2019-12-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0014_shouhuodizhi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingDan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sheng', models.CharField(default='', max_length=200, verbose_name='省')),
                ('Shi', models.CharField(default='', max_length=200, verbose_name='市')),
                ('Qu', models.CharField(default='', max_length=200, verbose_name='区')),
                ('JieDao', models.CharField(default='', max_length=200, verbose_name='街道')),
                ('DianHua', models.CharField(default='', max_length=200, verbose_name='电话')),
                ('XingMing', models.CharField(default='', max_length=200, verbose_name='姓名')),
                ('YouBian', models.CharField(default='', max_length=200, verbose_name='邮编')),
                ('ShangPinMing', models.CharField(default='', max_length=200, verbose_name='商品名')),
                ('JiaGe', models.CharField(default='', max_length=200, verbose_name='价格')),
                ('JianJie', models.CharField(default='', max_length=200, verbose_name='简介')),
                ('TuPian', models.CharField(default='', max_length=200, verbose_name='图片')),
                ('LeiXing', models.CharField(default='', max_length=200, verbose_name='类型')),
                ('ShuLiang', models.CharField(default='', max_length=200, verbose_name='数量')),
                ('SuoShuShangDian', models.CharField(default='', max_length=200, verbose_name='所属商店')),
                ('GouMaiRen', models.CharField(default='', max_length=200, verbose_name='购买人')),
                ('GouMaiShuLiang', models.CharField(default='', max_length=200, verbose_name='购买数量')),
                ('ZhuangTai', models.CharField(default='下单', max_length=200, verbose_name='状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '订单列表',
            },
        ),
    ]
