# Generated by Django 2.0 on 2019-12-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBaseModel', '0015_dingdan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingJia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PingJiaRen', models.CharField(default='', max_length=200, verbose_name='评价人')),
                ('PingJiaShiJian', models.CharField(default='', max_length=200, verbose_name='评价时间')),
                ('PingJiaNaRong', models.CharField(default='', max_length=200, verbose_name='评价内容')),
                ('PingJiaShangPin', models.CharField(default='', max_length=200, verbose_name='评价商品')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '评价列表',
            },
        ),
    ]
